using System.Runtime.InteropServices;

namespace MonoMod.RuntimeDetour.Platforms;

public class DetourNativeMonoPosixPlatform : IDetourNativePlatform
{
    public DetourNativeMonoPosixPlatform(IDetourNativePlatform inner)
    {
        throw new NotSupportedAnymoreException();
    }

    public void MakeWritable(IntPtr src, uint size)
    {
        throw new NotSupportedAnymoreException();
    }

    public void MakeExecutable(IntPtr src, uint size)
    {
        throw new NotSupportedAnymoreException();
    }

    public void MakeReadWriteExecutable(IntPtr src, uint size)
    {
        throw new NotSupportedAnymoreException();
    }

    public void FlushICache(IntPtr src, uint size)
    {
        throw new NotSupportedAnymoreException();
    }

    public NativeDetourData Create(IntPtr from, IntPtr to, byte? type)
    {
        throw new NotSupportedAnymoreException();
    }

    public void Free(NativeDetourData detour)
    {
        throw new NotSupportedAnymoreException();
    }

    public void Apply(NativeDetourData detour)
    {
        throw new NotSupportedAnymoreException();
    }

    public void Copy(IntPtr src, IntPtr dst, byte type)
    {
        throw new NotSupportedAnymoreException();
    }

    public IntPtr MemAlloc(uint size)
    {
        throw new NotSupportedAnymoreException();
    }

    public void MemFree(IntPtr ptr)
    {
        throw new NotSupportedAnymoreException();
    }

    [DllImport("MonoPosixHelper", EntryPoint = "Mono_Posix_Syscall_sysconf", SetLastError = true)]
    public static extern long sysconf(SysconfName name, Errno defaultError);

    public enum SysconfName
    {
        _SC_ARG_MAX = 0,
        _SC_CHILD_MAX = 1,
        _SC_CLK_TCK = 2,
        _SC_NGROUPS_MAX = 3,
        _SC_OPEN_MAX = 4,
        _SC_STREAM_MAX = 5,
        _SC_TZNAME_MAX = 6,
        _SC_JOB_CONTROL = 7,
        _SC_SAVED_IDS = 8,
        _SC_REALTIME_SIGNALS = 9,
        _SC_PRIORITY_SCHEDULING = 10,
        _SC_TIMERS = 11,
        _SC_ASYNCHRONOUS_IO = 12,
        _SC_PRIORITIZED_IO = 13,
        _SC_SYNCHRONIZED_IO = 14,
        _SC_FSYNC = 15,
        _SC_MAPPED_FILES = 16,
        _SC_MEMLOCK = 17,
        _SC_MEMLOCK_RANGE = 18,
        _SC_MEMORY_PROTECTION = 19,
        _SC_MESSAGE_PASSING = 20,
        _SC_SEMAPHORES = 21,
        _SC_SHARED_MEMORY_OBJECTS = 22,
        _SC_AIO_LISTIO_MAX = 23,
        _SC_AIO_MAX = 24,
        _SC_AIO_PRIO_DELTA_MAX = 25,
        _SC_DELAYTIMER_MAX = 26,
        _SC_MQ_OPEN_MAX = 27,
        _SC_MQ_PRIO_MAX = 28,
        _SC_VERSION = 29,
        _SC_PAGESIZE = 30,
        _SC_RTSIG_MAX = 31,
        _SC_SEM_NSEMS_MAX = 32,
        _SC_SEM_VALUE_MAX = 33,
        _SC_SIGQUEUE_MAX = 34,
        _SC_TIMER_MAX = 35,
        _SC_BC_BASE_MAX = 36,
        _SC_BC_DIM_MAX = 37,
        _SC_BC_SCALE_MAX = 38,
        _SC_BC_STRING_MAX = 39,
        _SC_COLL_WEIGHTS_MAX = 40,
        _SC_EQUIV_CLASS_MAX = 41,
        _SC_EXPR_NEST_MAX = 42,
        _SC_LINE_MAX = 43,
        _SC_RE_DUP_MAX = 44,
        _SC_CHARCLASS_NAME_MAX = 45,
        _SC_2_VERSION = 46,
        _SC_2_C_BIND = 47,
        _SC_2_C_DEV = 48,
        _SC_2_FORT_DEV = 49,
        _SC_2_FORT_RUN = 50,
        _SC_2_SW_DEV = 51,
        _SC_2_LOCALEDEF = 52,
        _SC_PII = 53,
        _SC_PII_XTI = 54,
        _SC_PII_SOCKET = 55,
        _SC_PII_INTERNET = 56,
        _SC_PII_OSI = 57,
        _SC_POLL = 58,
        _SC_SELECT = 59,
        _SC_UIO_MAXIOV = 60,
        _SC_IOV_MAX = 60,
        _SC_PII_INTERNET_STREAM = 61,
        _SC_PII_INTERNET_DGRAM = 62,
        _SC_PII_OSI_COTS = 63,
        _SC_PII_OSI_CLTS = 64,
        _SC_PII_OSI_M = 65,
        _SC_T_IOV_MAX = 66,
        _SC_THREADS = 67,
        _SC_THREAD_SAFE_FUNCTIONS = 68,
        _SC_GETGR_R_SIZE_MAX = 69,
        _SC_GETPW_R_SIZE_MAX = 70,
        _SC_LOGIN_NAME_MAX = 71,
        _SC_TTY_NAME_MAX = 72,
        _SC_THREAD_DESTRUCTOR_ITERATIONS = 73,
        _SC_THREAD_KEYS_MAX = 74,
        _SC_THREAD_STACK_MIN = 75,
        _SC_THREAD_THREADS_MAX = 76,
        _SC_THREAD_ATTR_STACKADDR = 77,
        _SC_THREAD_ATTR_STACKSIZE = 78,
        _SC_THREAD_PRIORITY_SCHEDULING = 79,
        _SC_THREAD_PRIO_INHERIT = 80,
        _SC_THREAD_PRIO_PROTECT = 81,
        _SC_THREAD_PROCESS_SHARED = 82,
        _SC_NPROCESSORS_CONF = 83,
        _SC_NPROCESSORS_ONLN = 84,
        _SC_PHYS_PAGES = 85,
        _SC_AVPHYS_PAGES = 86,
        _SC_ATEXIT_MAX = 87,
        _SC_PASS_MAX = 88,
        _SC_XOPEN_VERSION = 89,
        _SC_XOPEN_XCU_VERSION = 90,
        _SC_XOPEN_UNIX = 91,
        _SC_XOPEN_CRYPT = 92,
        _SC_XOPEN_ENH_I18N = 93,
        _SC_XOPEN_SHM = 94,
        _SC_2_CHAR_TERM = 95,
        _SC_2_C_VERSION = 96,
        _SC_2_UPE = 97,
        _SC_XOPEN_XPG2 = 98,
        _SC_XOPEN_XPG3 = 99,
        _SC_XOPEN_XPG4 = 100,
        _SC_CHAR_BIT = 101,
        _SC_CHAR_MAX = 102,
        _SC_CHAR_MIN = 103,
        _SC_INT_MAX = 104,
        _SC_INT_MIN = 105,
        _SC_LONG_BIT = 106,
        _SC_WORD_BIT = 107,
        _SC_MB_LEN_MAX = 108,
        _SC_NZERO = 109,
        _SC_SSIZE_MAX = 110,
        _SC_SCHAR_MAX = 111,
        _SC_SCHAR_MIN = 112,
        _SC_SHRT_MAX = 113,
        _SC_SHRT_MIN = 114,
        _SC_UCHAR_MAX = 115,
        _SC_UINT_MAX = 116,
        _SC_ULONG_MAX = 117,
        _SC_USHRT_MAX = 118,
        _SC_NL_ARGMAX = 119,
        _SC_NL_LANGMAX = 120,
        _SC_NL_MSGMAX = 121,
        _SC_NL_NMAX = 122,
        _SC_NL_SETMAX = 123,
        _SC_NL_TEXTMAX = 124,
        _SC_XBS5_ILP32_OFF32 = 125,
        _SC_XBS5_ILP32_OFFBIG = 126,
        _SC_XBS5_LP64_OFF64 = 127,
        _SC_XBS5_LPBIG_OFFBIG = 128,
        _SC_XOPEN_LEGACY = 129,
        _SC_XOPEN_REALTIME = 130,
        _SC_XOPEN_REALTIME_THREADS = 131,
        _SC_ADVISORY_INFO = 132,
        _SC_BARRIERS = 133,
        _SC_BASE = 134,
        _SC_C_LANG_SUPPORT = 135,
        _SC_C_LANG_SUPPORT_R = 136,
        _SC_CLOCK_SELECTION = 137,
        _SC_CPUTIME = 138,
        _SC_THREAD_CPUTIME = 139,
        _SC_DEVICE_IO = 140,
        _SC_DEVICE_SPECIFIC = 141,
        _SC_DEVICE_SPECIFIC_R = 142,
        _SC_FD_MGMT = 143,
        _SC_FIFO = 144,
        _SC_PIPE = 145,
        _SC_FILE_ATTRIBUTES = 146,
        _SC_FILE_LOCKING = 147,
        _SC_FILE_SYSTEM = 148,
        _SC_MONOTONIC_CLOCK = 149,
        _SC_MULTI_PROCESS = 150,
        _SC_SINGLE_PROCESS = 151,
        _SC_NETWORKING = 152,
        _SC_READER_WRITER_LOCKS = 153,
        _SC_SPIN_LOCKS = 154,
        _SC_REGEXP = 155,
        _SC_REGEX_VERSION = 156,
        _SC_SHELL = 157,
        _SC_SIGNALS = 158,
        _SC_SPAWN = 159,
        _SC_SPORADIC_SERVER = 160,
        _SC_THREAD_SPORADIC_SERVER = 161,
        _SC_SYSTEM_DATABASE = 162,
        _SC_SYSTEM_DATABASE_R = 163,
        _SC_TIMEOUTS = 164,
        _SC_TYPED_MEMORY_OBJECTS = 165,
        _SC_USER_GROUPS = 166,
        _SC_USER_GROUPS_R = 167,
        _SC_2_PBS = 168,
        _SC_2_PBS_ACCOUNTING = 169,
        _SC_2_PBS_LOCATE = 170,
        _SC_2_PBS_MESSAGE = 171,
        _SC_2_PBS_TRACK = 172,
        _SC_SYMLOOP_MAX = 173,
        _SC_STREAMS = 174,
        _SC_2_PBS_CHECKPOINT = 175,
        _SC_V6_ILP32_OFF32 = 176,
        _SC_V6_ILP32_OFFBIG = 177,
        _SC_V6_LP64_OFF64 = 178,
        _SC_V6_LPBIG_OFFBIG = 179,
        _SC_HOST_NAME_MAX = 180,
        _SC_TRACE = 181,
        _SC_TRACE_EVENT_FILTER = 182,
        _SC_TRACE_INHERIT = 183,
        _SC_TRACE_LOG = 184,
        _SC_LEVEL1_ICACHE_SIZE = 185,
        _SC_LEVEL1_ICACHE_ASSOC = 186,
        _SC_LEVEL1_ICACHE_LINESIZE = 187,
        _SC_LEVEL1_DCACHE_SIZE = 188,
        _SC_LEVEL1_DCACHE_ASSOC = 189,
        _SC_LEVEL1_DCACHE_LINESIZE = 190,
        _SC_LEVEL2_CACHE_SIZE = 191,
        _SC_LEVEL2_CACHE_ASSOC = 192,
        _SC_LEVEL2_CACHE_LINESIZE = 193,
        _SC_LEVEL3_CACHE_SIZE = 194,
        _SC_LEVEL3_CACHE_ASSOC = 195,
        _SC_LEVEL3_CACHE_LINESIZE = 196,
        _SC_LEVEL4_CACHE_SIZE = 197,
        _SC_LEVEL4_CACHE_ASSOC = 198,
        _SC_LEVEL4_CACHE_LINESIZE = 199,
    }

    public enum Errno
    {
        EPERM = 1,
        ENOENT = 2,
        ESRCH = 3,
        EINTR = 4,
        EIO = 5,
        ENXIO = 6,
        E2BIG = 7,
        ENOEXEC = 8,
        EBADF = 9,
        ECHILD = 10,
        EAGAIN = 11,
        ENOMEM = 12,
        EACCES = 13,
        EFAULT = 14,
        ENOTBLK = 15,
        EBUSY = 16,
        EEXIST = 17,
        EXDEV = 18,
        ENODEV = 19,
        ENOTDIR = 20,
        EISDIR = 21,
        EINVAL = 22,
        ENFILE = 23,
        EMFILE = 24,
        ENOTTY = 25,
        ETXTBSY = 26,
        EFBIG = 27,
        ENOSPC = 28,
        ESPIPE = 29,
        EROFS = 30,
        EMLINK = 31,
        EPIPE = 32,
        EDOM = 33,
        ERANGE = 34,
        EDEADLK = 35,
        ENAMETOOLONG = 36,
        ENOLCK = 37,
        ENOSYS = 38,
        ENOTEMPTY = 39,
        ELOOP = 40,
        EWOULDBLOCK = 11,
        ENOMSG = 42,
        EIDRM = 43,
        ECHRNG = 44,
        EL2NSYNC = 45,
        EL3HLT = 46,
        EL3RST = 47,
        ELNRNG = 48,
        EUNATCH = 49,
        ENOCSI = 50,
        EL2HLT = 51,
        EBADE = 52,
        EBADR = 53,
        EXFULL = 54,
        ENOANO = 55,
        EBADRQC = 56,
        EBADSLT = 57,
        EDEADLOCK = 35,
        EBFONT = 59,
        ENOSTR = 60,
        ENODATA = 61,
        ETIME = 62,
        ENOSR = 63,
        ENONET = 64,
        ENOPKG = 65,
        EREMOTE = 66,
        ENOLINK = 67,
        EADV = 68,
        ESRMNT = 69,
        ECOMM = 70,
        EPROTO = 71,
        EMULTIHOP = 72,
        EDOTDOT = 73,
        EBADMSG = 74,
        EOVERFLOW = 75,
        ENOTUNIQ = 76,
        EBADFD = 77,
        EREMCHG = 78,
        ELIBACC = 79,
        ELIBBAD = 80,
        ELIBSCN = 81,
        ELIBMAX = 82,
        ELIBEXEC = 83,
        EILSEQ = 84,
        ERESTART = 85,
        ESTRPIPE = 86,
        EUSERS = 87,
        ENOTSOCK = 88,
        EDESTADDRREQ = 89,
        EMSGSIZE = 90,
        EPROTOTYPE = 91,
        ENOPROTOOPT = 92,
        EPROTONOSUPPORT = 93,
        ESOCKTNOSUPPORT = 94,
        EOPNOTSUPP = 95,
        EPFNOSUPPORT = 96,
        EAFNOSUPPORT = 97,
        EADDRINUSE = 98,
        EADDRNOTAVAIL = 99,
        ENETDOWN = 100,
        ENETUNREACH = 101,
        ENETRESET = 102,
        ECONNABORTED = 103,
        ECONNRESET = 104,
        ENOBUFS = 105,
        EISCONN = 106,
        ENOTCONN = 107,
        ESHUTDOWN = 108,
        ETOOMANYREFS = 109,
        ETIMEDOUT = 110,
        ECONNREFUSED = 111,
        EHOSTDOWN = 112,
        EHOSTUNREACH = 113,
        EALREADY = 114,
        EINPROGRESS = 115,
        ESTALE = 116,
        EUCLEAN = 117,
        ENOTNAM = 118,
        ENAVAIL = 119,
        EISNAM = 120,
        EREMOTEIO = 121,
        EDQUOT = 122,
        ENOMEDIUM = 123,
        EMEDIUMTYPE = 124,
        ECANCELED = 125,
        ENOKEY = 126,
        EKEYEXPIRED = 127,
        EKEYREVOKED = 128,
        EKEYREJECTED = 129,
        EOWNERDEAD = 130,
        ENOTRECOVERABLE = 131,
        EPROCLIM = 1067,
        EBADRPC = 1072,
        ERPCMISMATCH = 1073,
        EPROGUNAVAIL = 1074,
        EPROGMISMATCH = 1075,
        EPROCUNAVAIL = 1076,
        EFTYPE = 1079,
        EAUTH = 1080,
        ENEEDAUTH = 1081,
        EPWROFF = 1082,
        EDEVERR = 1083,
        EBADEXEC = 1085,
        EBADARCH = 1086,
        ESHLIBVERS = 1087,
        EBADMACHO = 1088,
        ENOATTR = 1093,
        ENOPOLICY = 1103,
    }
}
